### ISSUE TITLE
wrong conflicts in the module file

### ISSUE THREAD

**Issue by mcytowski** [Pawseyops/maali#41] opened 2017-12-11 06:04 UTC
I've created a cyg file for NAMD 2.12 but after using it with maali/1.4.1 I get the following in my module file:
Compiled with intel/17.0.5
Compiled for sandybridge
Compiled for broadwell
Compiled for knl
Compiled for CUDA with cuda
...
conflict sandybridge
conflict broadwell
conflict knl
conflict (D)
conflict gcc/5.5.0
conflict gcc/7.2.0
conflict libjpeg-turbo/1.5.2
conflict libjpeg-turbo/1.5.2
conflict cuda/8.0
conflict libjpeg-turbo/1.5.2

so, I am not able to load the module cause it conflicts with everything it was compiled with.
The .cyg file is attached as a .txt. 
[namd.txt](https://github.com/Pawseyops/maali/files/1546678/namd.txt)

**Comment by schibeci** [comment] 2017-12-11 08:23
Hi Maciej,

Can you try running with the -l flag?

I think the issue is in the TCL module conflict code.

Yours sincerely,
David

**Comment by mcytowski** [comment] 2017-12-11 09:10
Hi David,
it is a bit better now, but seems that cuda is still in conflict list:
...
whatis( [[Compiled with intel/17.0.5]] )
whatis( [[Compiled for sandybridge]] )
whatis( [[Compiled for broadwell]] )
whatis( [[Compiled for knl]] )
whatis( [[Compiled for CUDA with cuda]] )
conflict("ivybridge")
conflict("haswell")
conflict("gcc/5.5.0")
conflict("gcc/7.2.0")
conflict(cuda/8.0)
conflict(libjpeg-turbo/1.5.2)

if (mode() == "load") then
  if (isloaded("cuda") ~= true) then
    load("cuda/8.0")
  end
end
load("fftw")
....

I am also having different issues:
mcytowski@zeus-1:/group/pawsey0001/mcytowski/tmp2> module load namd-gpu
Lmod has detected the following error: Unable to load module:
     /group/pawsey0001/mcytowski/software/sles12sp3/modulefiles/namd-gpu/2.12.lua: [string "help("Sets up the paths you need to use namd ..."]:23: malformed number near '1.5.2'

While processing the following module(s):
    Module fullname  Module Filename
    ---------------  ---------------
    namd-gpu/2.12    /group/pawsey0001/mcytowski/software/sles12sp3/modulefiles/namd-gpu/2.12.lua

Which is related to the first line in the lua file:
help("Sets up the paths you need to use namd version 2.12")

Best regards,
Maciej

**Comment by schibeci** [comment] 2017-12-12 04:39
Hi Maciej,

I have checked in some code to fix the issue on Zeus.

You should be able to run it using -m to just re-created the module file.

Make sure you use "$MAALI_DEFAULT_CUDA_COMPILERS" for the cuda version (or make sure you have cuda/8.0 listed with the version).

Yours sincerely,
David

**Comment by mcytowski** [comment] 2017-12-12 05:01
Hi David,

it is working fine now. Thanks!

I will probably have to rebuild it since I have all installed in:
/group/pawsey0001/mcytowski/software/sles12sp3/apps/broadwell/intel/17.0.5/cuda/namd-gpu/2.12
instead of
/group/pawsey0001/mcytowski/software/sles12sp3/apps/broadwell/intel/17.0.5/cuda/8.0/namd-gpu/2.12/

Kind regards,
Maciej

**Closed as completed** 2017-12-18 08:32 UTC
